name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: golang_lint_and_test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: setup Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      # Get values for cache paths to be used in later steps
      # Based on: https://markphelps.me/posts/speed-up-your-go-builds-with-actions-cache/
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E gofmt
      - name: run Unit tests.
        run: go test ./...
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "anw"
          skip: "go.mod,go.sum,Makefile,docker-compose.yml"