name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]

jobs:
  build:
    name: golang_lint_and_test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: setup Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E gofmt
      - name: run Unit tests.
        run: cd ./account && go test ./... -v
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "anw"
          skip: "go.mod,go.sum,Makefile,docker-compose.yml"