name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Continuos Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: setup Go
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: ^1.18
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Build
        run: go build .
#      - name: Run Golang CI Lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          version: latest
#          args: -E gofmt
      - name: run Unit tests.
        working-directory: ./account
        run: go test -v -cover ./...

  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "anw"
          skip: "go.mod,go.sum,Makefile,docker-compose.yml"