name: codecov
on: [push]
jobs:

  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Generate coverage report
        run: |
          go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: {{your codecov token, can be found at https://codecov.io/gh/<github_username>/<repo>/settings/badge}}
          file: ./coverage.txt
          flags: unittests